language: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t mdesmos/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mdesmos/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-545239612193"
    bucket_path: "Docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"