language: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t mdesmos/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mdesmos/docker-react npm run test

